### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/libreddit_ynh#41] opened 2023-06-04 18:41 UTC
```
Installing libreddit...
Provisionning sources...
Failed to provision sources : YunoHost was able to download the asset 'main' (https://github.com/spikecodes/libreddit/releases/download/v0.30.1/libreddit) for libreddit, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and update the app manifest to reflect this change.
Expected sha256 checksum: d9b3cbc278b0427904e1c414441fd8daa355eacec471e33e027dd0694ce68e8b
Downloaded sha256 checksum: 9bba0a2bc4fc18d2f27d3793359f700921ebe1812c59623d83e04d2e39cfec28
Downloaded file size: 6.9M
Deprovisionning sources...
Provisioning, deprovisioning, or updating resources for libreddit failed: YunoHost was able to download the asset 'main' (https://github.com/spikecodes/libreddit/releases/download/v0.30.1/libreddit) for libreddit, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and update the app manifest to reflect this change.
Expected sha256 checksum: d9b3cbc278b0427904e1c414441fd8daa355eacec471e33e027dd0694ce68e8b
Downloaded sha256 checksum: 9bba0a2bc4fc18d2f27d3793359f700921ebe1812c59623d83e04d2e39cfec28
Downloaded file size: 6.9M
```
https://paste.yunohost.org/raw/vutidapiwu

I wonder if anyone can replicate this. I use the YNH 11.1.20 (stable)

**Comment by sekretaerbaer** [comment] 2023-06-07 06:12
Here comes exactly the same error message.

The sha256 checksum has changed 4 days ago. (https://github.com/libreddit/libreddit/releases/tag/v0.30.1)
and the URL of the github repo has apparently also changed to https://github.com/libreddit/libreddit

**Comment by ericgaspar** [comment] 2023-06-07 06:26
should be fixed with #42

**Comment by sekretaerbaer** [comment] 2023-06-08 07:36
installation has worked but now the service does not start.

https://github.com/YunoHost-Apps/libreddit_ynh/issues/43

**Comment by ericgaspar** [comment] 2023-06-08 08:10
The upstream binary was built with a newer library (libc6) than the one provided by Debian Bullseye...
https://github.com/libreddit/libreddit/issues/820

**Comment by ericgaspar** [comment] 2023-06-08 09:02
It is better to revert to 0.30.0 untill the issue get solved upstream or when we get the BookwormDebian update.

**Comment by sigaloid** [comment] 2023-06-09 15:39
This is caused by https://github.com/libreddit/libreddit/issues/813, an accidental issue with our CI building and replacing the tagged release 0.30.1 when it shouldn't have been.
~~Would you mind testing on this binary? I changed the build script to build statically. https://github.com/libreddit/libreddit/actions/runs/5171452941~~
~~Actually, that's the nightly, let me compile the 0.30.1 version to keep it accurate.~~

[libreddit-0.30.1.zip](https://github.com/YunoHost-Apps/libreddit_ynh/files/11707970/libreddit-0.30.1.zip)


---
Ok, I tested it myself, the new binary works. The 0.30.1 tagged release's binary now runs on debian:bullseye-slim since it's compiled statically. I

**Comment by ericgaspar** [comment] 2024-08-14 17:07
closing with #53

**Closed as completed by ericgaspar** 2024-08-14 17:07 UTC
